server:
  port: 8087
spring:
  application:
    name: exam
  datasource:
    url: jdbc:mysql://localhost:3306/rules_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: secret
  # Specify the master changelog file
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    # Optional: Set to false if you don't want Liquibase to run on startup
    enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
logging:
  level:
    org:
      springframework:
        web: INFO